sudo: required
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
before_install:
  - wget https://github.com/spf13/hugo/releases/download/v0.14/hugo_0.14_i386.deb
  - sudo dpkg -i hugo_0.14_i386.deb
  - npm install -g npm@'>2.11.0'
after_script:
  - CODECLIMATE_REPO_TOKEN=5b9d2275eb7937ba2e45b931eccc0b4b6cb6e48a9d4d234e3b008b87616b4e0a codeclimate < coverage/lcov.info
